# persair

# Abstract

`persair` is a python command line client and module for interacting with the PurpleAir API. A set of convenience commands are also available in the `nushell` based `persair.nu` script. Typical functions provided include collecting information on specific sensors as well as checking on when a specific sensor last checked in to the Purple API servers. `persair` also offers convenient _sensor-group_ based operations, collecting data from a set of sensors in the PurpleAir network.

This document describes the _Installation_ and _Use_ of `persair`.

# Introduction

PurpleAir is a community-owned system of sensors that measure particulate matter in the atmosphere. Sample data is uploaded to PurpleAir in real time and information is shown in a web-based geographic UI, allowing for close-to-realtime monitoring of air quality across the https://map.purpleair.com/[sensor network].

Current and historical data from individual sensors can also be accessed from the https://api.purpleair.com[PurpleAir API] by any client application that is authenticated to the API service. Authentication is performed by using read and write "keys" available from the http://develop.purpleair.com[PurpleAir develop portal]. While these authentication keys are freely available, each call to the API carries a "cost" in "tokens" (different calls cost different "amounts"). While PurpleAir provides a number of tokens for free, once exhausted users need to purchase more tokens.

Accessing the API for data from a given sensor requires not only read and write keys, but also somewhat sophisticated knowledge from a user to use a web-based API. In order to simplify this access, `persair` was created as a terminal-application that provides a simple command-line interface to interacting with the API. In addition to the application itself, several convenience functions are available in a `nushell` environment.

In this document you will need to use a terminal application to run `persair`. Commands that you need to type in the terminal are show in source block:

[source, shell]
----
# This is a shell "source" block. In this shell, lines that start with
# a "hash" (#) are considered comments and are for illustrative purposes.
# Any shell "commands" that should be typed into a terminal will appear
# in a line of their own without a leading hash character. In the next line,
# the "someCommand" is command to type, the "--withAFlag" is a command line
# flag, and the "value" the value for that flag:

someCommand --withAFlag value
----

# Installation

Several installation steps are required to use `persair`, typical of most command line python applications. Usually these assume a "UNIX" (Linux or macOS) operating system, however instructions/pointers for Windows systems are also provided. The steps are:

- install python (usually included by default on Linux and macOS);
- create a python _virtual environment_ in which to install `persair`;
- install `persair`
- get/use PurpleAir API read/write keys.

These steps are generally not complex, and are discussed next.

## Extra credit

While not _required_, it is also highly _suggested_ to also install `nushell` as the command line interpreter in your terminal (see below). There are several convenience scripts offered by this repository that leverage the excellent JSON parsing and presentation abilities of `nushell`.

## Linux and macOS

UNIX type systems, including Linux and macOS, have Python already installed and available out of the box.

## Windows

Windows typically does not by default have a Python installation, but Python is available in the Microsoft Store. Please consult the store for installation.

Alternatively, Python can also be downloaded and installed from the official https://www.python.org/downloads/[Python website].

## Virtual Environment

A Python _virtual environment_ is recommended for using `persair`. A virtual environment allows you to isolate Python packages for different projects, which helps prevent conflicts between packages and ensures a clean environment for each Python project.

The steps to create a virtual environment are largely the same in all operating systems, differing only in some syntax (Windows uses a backslash to separate directories in a terminal `\` while Linux and macOS use a forward slash `/`):

- open a terminal;
- navigate to a (or _create_) a directory to contain the virtual environment;
- run the python virtual environment creation command;
- _activate_ the virtual environment;
- use the `pip` (Preferred Installer Program) command to install `persair` and its dependencies.

### Linux, macOS and Windows

[source, shell]
----
# If you don't have a directory yet in which to create the
# virtual environment, we suggest creating a parent and child
# folder:

# Go to your home directory
cd ~

# Make a directory (folder) to hold all your python virtual
# environments
mkdir penv

# Enter that directory
cd penv

# And finally, create an environment for persair, here
# caller pair:
python -m venv pair
----

### _Activate_ the `pair` env

[source, shell]
----
# In Linux and macOS:

cd ~/
source penv/pair/bin/activate

# In Windows:
cd ~
penv/pair/Scripts/activate
----

In both cases, you will notice that your prompt has changed and should indicate `pair`.


## Install `persair`

Now you can finally install `persair`. In your terminal with the `pair` environment activated, simply do

[source, shell]
----
pip install persair
----

and `persair` should now be installed!.

